### ISSUE TITLE
Do I have to declare custom tags document.registerElement ?

### ISSUE THREAD

**Issue by lud** [rsms/raster#6]
It seems not, but how do I know it would work on all browsers ?

Maybe the docs should have a little paragraph about it.

**Comment by heyallan** [comment]
Custom elements are still valid elements. No need to register them via JS if they won't feature any dynamic behaviour. 

However the proposed syntax for custom elements is `<prefix-tagname>` as in `<grid-container>`, `<grid-column>`, `<foo-bar>`. Browsers accept custom elements using `HTMLElement` interface, or the `HTMLUnknownElement` interface, which is "invalid" but still works because it inherits from `HTMLElement`, it just won't have a semantic value, nor specific properties (similar to a `<span>`). Also W3 validator accepts custom elements as long as they use a dash in the name. Most importantly the browser won't crash, it will just render an inline, unstyled, element without semantic value.

Reference:

- [Custom Elements (MDN)](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements)
- [HTMLUnknownElement (MDN)](https://developer.mozilla.org/en-US/docs/Web/API/HTMLUnknownElement) - [Browser Support (CanIUse)](https://caniuse.com/#feat=mdn-api_htmlunknownelement)
- [HTMLElement (MDN)](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) - [Browser Support (CanIUse)](https://caniuse.com/#feat=mdn-api_htmlelement)
- [Validator test (W3)](https://validator.w3.org/nu/#textarea)

**Comment by lud** [comment]
Ok thank you
